#pragma once

#define OFFSET_HALO3ODST_PF_ENGINE 0xC0520//0xC0424
#define OFFSET_HALO3ODST_PF_WORLD 0x109F78//0x109E70
#define OFFSET_HALO3ODST_PF_RENDER 0x1B4708//0x1B4608

#define OFFSET_HALO3ODST_PF_COOP_JOIN 0x1258C

#define OFFSET_HALO3ODST_PF_ADD_LOCAL_PLAYER 0xFBFE4//0xFBEE4

#define OFFSET_HALO3ODST_V_ENTRY_PLAYERS 0x2
#define OFFSET_HALO3ODST_V_ENTRY_PLAYERS_ACTION 0xB

// spawning (the Halo 3 functions and globals of the same names, matched by signature and call order)
#define OFFSET_HALO3ODST_PV_TAGS_HEADER 0x20F3068
#define OFFSET_HALO3ODST_PV_TAG_BASE 0x2022AA8
#define OFFSET_HALO3ODST_PV_TAG_NAMES 0xA9EFC8
#define OFFSET_HALO3ODST_PV_SCENARIO 0xA9C9B8
#define OFFSET_HALO3ODST_PF_OBJECT_PLACEMENT_DATA_NEW 0x37C954
#define OFFSET_HALO3ODST_PF_OBJECT_NEW 0x37CF34
#define OFFSET_HALO3ODST_PF_OBJECT_POST_CREATE 0x20B80
#define OFFSET_HALO3ODST_PF_AI_PLACE 0x5BE6A0 // (int ai_index, bool); ai index type 4 = a squad's single location
#define OFFSET_HALO3ODST_PF_TAG_LOADED 0x14D4C8 // bool (int tag): in the loaded zone set (object_new refuses others)

// per-player HUD (mcc/hud)
#define OFFSET_HALO3ODST_PV_HUD_DRAWING_PLAYER 0xB1AA04 // int user whose HUD is being drawn
#define OFFSET_HALO3ODST_PV_HUD_CANVAS 0xB1A9D8 // float width, height of that user's HUD virtual canvas

// Left/Right split screen (mcc/splitscreen/LeftRight); see offset_halo3.h for the signatures
#define OFFSET_HALO3ODST_PV_SPLITSCREEN_TABLE 0x8F1F10
#define OFFSET_HALO3ODST_PV_SCREEN_SIZE 0x8F0278
#define OFFSET_HALO3ODST_PF_SPLITSCREEN_PLAYER_COUNT 0x313AF0
#define OFFSET_HALO3ODST_PF_DRAW_SPLITSCREEN_BARS 0x303C54
#define OFFSET_HALO3ODST_PF_FILL_RECT 0x1BA498
#define OFFSET_HALO3ODST_PF_RT_CREATE 0x2A2C64 // (target*, int sizes[], descriptor*, int variant, int)
#define OFFSET_HALO3ODST_PF_RT_POOL_RELEASE 0x2A3400
#define OFFSET_HALO3ODST_PF_RT_POOL_INIT 0x2A30F0
#define OFFSET_HALO3ODST_PF_HUD_RESOLUTION 0x32DD0C
#define OFFSET_HALO3ODST_PF_HUD_LAYOUT 0x3284B4 // record* - +0x94 int canvas width, height; 0x110 bytes
