// Every module's offsets and the byte patterns to find them by in another build (generated by
// tools/offsets/gen_patterns.py into lib/game/inc/<version>/patterns_*.inc).
#include "Tables.h"

#include <iterator>

#include "offset_groundhog.h"
#include "offset_halo1.h"
#include "offset_halo2.h"
#include "offset_halo3.h"
#include "offset_halo3odst.h"
#include "offset_halo4.h"
#include "offset_haloreach.h"
#include "offset_mcc.h"

namespace AlphaRing::Offsets {
    namespace {
#include "patterns_halo1.inc"
#include "patterns_halo2.inc"
#include "patterns_halo3.inc"
#include "patterns_halo4.inc"
#include "patterns_groundhog.inc"
#include "patterns_halo3odst.inc"
#include "patterns_haloreach.inc"
#include "patterns_mcc.inc"
    }

    const ModuleTable kTables[kModuleCount] = {
        {"halo1", kHalo1Build, kHalo1Patterns, std::size(kHalo1Patterns)},
        {"halo2", kHalo2Build, kHalo2Patterns, std::size(kHalo2Patterns)},
        {"halo3", kHalo3Build, kHalo3Patterns, std::size(kHalo3Patterns)},
        {"halo4", kHalo4Build, kHalo4Patterns, std::size(kHalo4Patterns)},
        {"groundhog", kGroundhogBuild, kGroundhogPatterns, std::size(kGroundhogPatterns)},
        {"halo3odst", kHalo3odstBuild, kHalo3odstPatterns, std::size(kHalo3odstPatterns)},
        {"haloreach", kHaloreachBuild, kHaloreachPatterns, std::size(kHaloreachPatterns)},
        {"MCC-Win64-Shipping", kMccBuild, kMccPatterns, std::size(kMccPatterns)},
    };
}
